include:
  - deployment/hdfs.yaml
  - deployment/kafka.yaml
  - deployment/spark.yaml
  - deployment/mongodb.yaml
  - deployment/serving.yaml

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 1000
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    networks:
      - net

networks:
  net:
    driver: bridge