services:
  mongo1:
    image: mongo:5
    container_name: mongo1
    networks:
      - net
    command: mongod --replSet myReplicaSet --bind_ip_all
    # ports:
    #   - 27017:27017
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:5
    container_name: mongo2
    networks:
      - net
    command: mongod --replSet myReplicaSet --bind_ip_all
    volumes:
      - mongo2_data:/data/db
    # ports:
    #   - 27018:27017

  mongo3:
    image: mongo:5
    container_name: mongo3
    networks:
      - net
    command: mongod --replSet myReplicaSet --bind_ip_all
    volumes:
      - mongo3_data:/data/db
    # ports:
    #   - 27019:27017

  mongo-init:
    image: mongo:5
    container_name: mongo-init
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - net
    entrypoint: >
      bash -c "sleep 10;
               mongosh --host mongo1 --eval 'rs.initiate({
                  _id: \"myReplicaSet\",
                  members: [
                    { _id: 0, host: \"mongo1:27017\" },
                    { _id: 1, host: \"mongo2:27017\" },
                    { _id: 2, host: \"mongo3:27017\" }
                  ]
               })' || true"

  # test_client:
  #   image: python:3.8
  #   container_name: test_client
  #   networks:
  #     - net
  #   command: bash -c "tail -f /dev/null"
  #   depends_on:
  #     - mongo1
  #     - mongo2
  #     - mongo3

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
