version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8085:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - net
      
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - net
    
  spark-client:
    image: bde2020/spark-client:3.5.0
    build: ../spark_client/
    container_name: spark-client
    depends_on:
      - spark-master
      - spark-worker-1
    ports:
      - "8888:8888"
    environment:
      - SPARK_MASTER_NAME=spark-master
      - SPARK_MASTER_PORT=7077
      # - SPARK_APPLICATION_PYTHON_LOCATION=""
      # - SPARK_APPLICATION_ARGS=""
    volumes:
      - ../data/spark-client:/app/data
    networks:
      - net